apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: ${var.aws_region}
    secureJsonData:
      accessKey: ${var.aws_access_key_id}
      secretKey: ${var.aws_secret_access_key}
    isDefault: true
