version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: votaciondb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  ms-logeo:
    build: ./ms-logeo
    container_name: ms-logeo
    restart: always
    depends_on:
      - db
    networks:
      - kong-net

  ms-participantes:
    build: ./ms-participantes
    container_name: ms-participantes
    restart: always
    depends_on:
      - db
    networks:
      - kong-net

  ms-votaciones:
    build: ./ms-votaciones
    container_name: ms-votaciones
    restart: always
    depends_on:
      - db
    networks:
      - kong-net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - ms-logeo
      - ms-participantes
      - ms-votaciones
    ports:
      - "8080:80"
    networks:
      - kong-net

  kong-database:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.4
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    image: kong:3.4
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"     # proxy
      - "8001:8001"     # admin
    networks:
      - kong-net

networks:
  kong-net:

volumes:
  kong-data:
