services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PVOT11
      MYSQL_DATABASE: bdpvot
      MYSQL_USER: myuser
      MYSQL_PASSWORD: BDMUR11
    ports:
      - "3306:3306"
    volumes:
    - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mynetwork

  apache:
    build: ./apache
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/src:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynetwork

  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  kong:
    image: kong
    container_name: kong
    restart: always
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"  # Habilitar PostgreSQL en lugar de modo declarativo
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"  
    ports:
      - "8000:8000"   
      - "8001:8001"   
      - "8443:8443"  # Admin API con SSL
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

